#requires -Version 5.1
<#
.SYNOPSIS
  Setup/repair checklist for the agent workflow on Windows 11.

.DESCRIPTION
  Idempotent. Personal tokens are NEVER touched.
  Steps:
    1. Check/install optional CLIs (gh, jq) when possible.
    2. Link shared agent skills via junction where needed.
    3. Generate per-agent contract bridges and personal-rules stub.
    4. Print manual next steps.
#>
param(
  [string]$Agent,
  [string]$SkillsDir,
  [string]$Entrypoint,
  [switch]$NoInstall
)
$ErrorActionPreference = 'Stop'

$knownAgents = @('claude', 'codex', 'cursor', 'windsurf', 'gemini', 'opencode', 'kiro', 'cline', 'pi', 'copilot', 'roo', 'warp')
if (-not $Agent) {
  Write-Host 'Specify agent, e.g. claude | codex | cursor | gemini | opencode | kiro | cline | pi' -ForegroundColor Red
  Write-Host '  example: powershell -File scripts\agent-assisted-setup.ps1 pi' -ForegroundColor Red
  exit 2
}
if (($knownAgents -notcontains $Agent) -and (-not $SkillsDir) -and (-not $Entrypoint)) {
  Write-Host "Unknown agent: $Agent" -ForegroundColor Red
  Write-Host '  For a new agent use -SkillsDir and/or -Entrypoint (Tier-2 fallback).' -ForegroundColor Red
  exit 2
}

$Root = (& git rev-parse --show-toplevel 2>$null)
if (-not $Root) { Write-Error 'Not a git repository.'; exit 1 }
Set-Location $Root

function Bold($m) { Write-Host $m -ForegroundColor White }
function Ok($m) { Write-Host "  + $m" -ForegroundColor Green }
function Skip($m) { Write-Host "  . $m" -ForegroundColor DarkGray }
function Warn($m) { Write-Host "  ! $m" -ForegroundColor Yellow }
function Have($c) { [bool](Get-Command $c -ErrorAction SilentlyContinue) }

function Link-SkillsJunction($rel) {
  $target = Join-Path $Root $rel
  $src = Join-Path $Root '.agents\skills'
  $parent = Split-Path $target -Parent
  New-Item -ItemType Directory -Force -Path $parent | Out-Null
  if (Test-Path $target) {
    $item = Get-Item $target -Force
    if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -eq 0) {
      Warn "$rel exists and is not a symlink/junction — leaving it untouched"
      return
    }
    $item.Delete()
  }
  New-Item -ItemType Junction -Path $target -Target $src | Out-Null
  Ok "skills linked: $rel -> .agents\skills"
}

function Link-PiPersonalBridge() {
  $target = Join-Path $Root '.pi\APPEND_SYSTEM.md'
  $src = Join-Path $Root 'ai\personal\AGENTS.md'
  New-Item -ItemType Directory -Force -Path (Join-Path $Root '.pi') | Out-Null
  if (Test-Path $target) {
    $item = Get-Item $target -Force
    if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { $item.Delete() }
    else { Warn '.pi/APPEND_SYSTEM.md already exists and is not a generated symlink — leaving it untouched'; return }
  }
  try {
    New-Item -ItemType SymbolicLink -Path $target -Target $src -ErrorAction Stop | Out-Null
    Ok '.pi/APPEND_SYSTEM.md -> ai/personal/AGENTS.md'
  }
  catch {
    Set-Content -Path $target -Value @(
      '# Windows fallback copy generated by scripts/agent-assisted-setup.ps1.',
      '# Re-run setup after editing ai/personal/AGENTS.md if symlinks are unavailable.',
      '',
      (Get-Content -Path $src -Raw)
    )
    Warn 'Could not create .pi/APPEND_SYSTEM.md symlink; wrote fallback copy.'
  }
}

Bold '1/4 · Optional CLI tools (gh, jq)'
function Install-Cli($bin, $wingetId, $scoopId, $name, $url) {
  if (Have $bin) { Ok "$name already installed"; return }
  if ($NoInstall) { Warn "$name not installed (skipped by -NoInstall)"; return }
  if ($wingetId -and (Have winget)) {
    winget install --silent --accept-package-agreements --accept-source-agreements -e --id $wingetId 2>$null
    if (Have $bin) { Ok "$name installed (winget)"; return }
  }
  if (Have scoop) {
    scoop install $scoopId 2>$null
    if (Have $bin) { Ok "$name installed (scoop)"; return }
  }
  Warn "$name not installed. Install manually: $url"
}
Install-Cli 'gh' 'GitHub.cli' 'gh' 'GitHub CLI' 'https://cli.github.com/'
Install-Cli 'jq' 'jqlang.jq' 'jq' 'jq' 'https://jqlang.github.io/jq/'

Bold "2/4 · Shared skills for: $Agent"
$linkMap = @{ claude = '.claude\skills'; kiro = '.kiro\skills'; cline = '.cline\skills' }
$nativeAgents = @('codex', 'cursor', 'windsurf', 'gemini', 'opencode', 'pi', 'copilot', 'roo', 'warp')
if ($SkillsDir) {
  Link-SkillsJunction ($SkillsDir -replace '/', '\')
  Warn "Tier-2: add '$SkillsDir' to .gitignore if it is local-only"
}
elseif ($linkMap.ContainsKey($Agent)) { Link-SkillsJunction $linkMap[$Agent] }
elseif ($nativeAgents -contains $Agent) { Ok "$Agent reads .agents/skills natively — no symlink needed" }
else { Skip "unknown agent '$Agent' for skills — pass -SkillsDir" }

Bold '3/4 · Personal rules and bridges'
if (Test-Path 'ai\personal\AGENTS.md') { Skip 'ai/personal/AGENTS.md already exists' }
else {
  New-Item -ItemType Directory -Force -Path 'ai\personal' | Out-Null
  Set-Content -Path 'ai\personal\AGENTS.md' -Value @(
    '# Local personal rules for this repository (gitignored).',
    '# Layered over root AGENTS.md; on conflict these rules win.',
    '# Add your rules below.'
  )
  Ok 'ai/personal/AGENTS.md created'
}

if ($Agent -eq 'pi') { Link-PiPersonalBridge }

if ($Agent -eq 'claude') {
  $ok = $false
  if (Test-Path 'CLAUDE.md') {
    $lines = Get-Content -Path 'CLAUDE.md' -ErrorAction SilentlyContinue
    $ok = ($lines -contains '@AGENTS.md') -and ($lines -contains '@ai/personal/AGENTS.md')
  }
  if ($ok) { Skip 'CLAUDE.md already configured' }
  else { Set-Content -Path 'CLAUDE.md' -Value @('@AGENTS.md', '@ai/personal/AGENTS.md'); Ok 'CLAUDE.md configured' }
}

if ($Agent -eq 'gemini') {
  $cfg = '.gemini\settings.json'
  if (Test-Path $cfg) {
    if (Select-String -Path $cfg -Pattern 'AGENTS.md' -Quiet) { Skip '.gemini/settings.json already references AGENTS.md' }
    else { Warn 'Add AGENTS.md to .gemini/settings.json context.fileName' }
  }
  else {
    New-Item -ItemType Directory -Force -Path '.gemini' | Out-Null
    Set-Content -Path $cfg -Value @('{', '  "context": {', '    "fileName": ["AGENTS.md", "GEMINI.md"]', '  }', '}')
    Ok '.gemini/settings.json configured'
  }
}

if ($Entrypoint) {
  if (Test-Path $Entrypoint) { Skip "$Entrypoint already exists — leaving it untouched" }
  else {
    $parent = Split-Path $Entrypoint -Parent
    if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
    try {
      New-Item -ItemType SymbolicLink -Path $Entrypoint -Target (Join-Path $Root 'AGENTS.md') -ErrorAction Stop | Out-Null
      Ok "$Entrypoint -> AGENTS.md"
      Warn "Tier-2: add '$Entrypoint' to .gitignore if it is local-only"
    }
    catch { Warn "Could not create symlink $Entrypoint; create bridge manually." }
  }
}

Bold '4/4 · Manual next steps'
Write-Host '  • If using GitHub, run: gh auth status  (or gh auth login)'
Write-Host '  • Verify branch/status: git branch --show-current && git status -sb'
Write-Host '  • For task context, use /session-start when requirements are unclear'
